// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fycbqtlycpgoultjnzul.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ5Y2JxdGx5Y3Bnb3VsdGpuenVsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwODUzNTksImV4cCI6MjA2NTY2MTM1OX0.xVnY9gaGL50AIwoybJMm0_ulmGSUD7vt2P2NaEycYTg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);